<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">

  <title>Exceptions</title>

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <link rel="stylesheet" href="reveal/css/reveal.css">
  <link rel="stylesheet" href="media/presentations.css" id="theme">
  <link rel="stylesheet" href="reveal/lib/css/zenburn.css">

  <!-- Printing and PDF exports -->
  <script>
    var link = document.createElement('link');
    link.rel = 'stylesheet';
    link.type = 'text/css';
    link.href = window.location.search.match(/print-pdf/gi) ? 'reveal/css/print/pdf.css' : 'reveal/css/print/paper.css';
    document.getElementsByTagName('head')[0].appendChild(link);
  </script>

  <style>
    .reveal .slide spre {
      width: 100%
    }
  </style>
</head>

<body>

  <div class="reveal">
    <div class="slides">
      <section data-background-size="cover" data-background-image="media/rose_background.jpg">
        <h1 class="slide_main_title"><b>Exceptions</b></h1>
      </section>
      <section>
        <section>
          <h1><b>
                <span>Catching Exceptions</span>
            </h1></b>
        </section>
        <section>
          <h3><b>Python handles all errors with exceptions</b></h3>
          <ul>
            <li>An exception is a signal that an error or other unusual condition has occurred.</li>
          </ul>
        </section>
        <section>
          <h3><b>Catching an Exception</b></h3>
          <pre><code data-trim data-noescape class="hljs">
try:
    execute_some_code()
except SomeException:
    handle_gracefully()
          </code></pre>
        </section>
        <section>
          <h3><b>Catching all Exceptions</b></h3>
          <pre><code data-trim data-noescape class="hljs">
try:
    execute_some_code()
except:
    handle_gracefully()
          </code></pre>
        </section>
        <section>
          <h3><b>Don't Do It!</b></h3>
          <ul>
            <li>Catching too broad exceptions is potentially dangerous.</li>
            <li>Among others, this "wildcard" handler will catch:</li>
              <ul>
                  <li>system exit triggers</li>
                  <li>memory errors</li>
                  <li>typos</li>
                  <li>anything else you might not have considered</li>
              </ul>
          </ul>
        </section>
        <section>
          <h3><b>Exercise: Divide by Zero</b></h3>
          <ul>
            <li>Try to divide 1/0. What happens?</li>
            <li>Catch the exception and tell the user he cannot divide by zero.</li>
          </ul>
        </section>
        <section>
          <h3><b>Catching Multiple Exceptions</b></h3>
          <ul>
            <li>Handling them all the same way</li>
          </ul>
          <pre><code data-trim data-noescape class="hljs">
try:
    execute_some_code()
except (SomeException, AnotherException):
    handle_gracefully()
          </code></pre>
        </section>
        <section>
          <h3><b>Catching Multiple Exceptions</b></h3>
          <ul>
            <li>Handling them separately</li>
          </ul>
          <pre><code data-trim data-noescape class="hljs">
try:
    execute_some_code()
except SomeException:
    handle_gracefully()
except AnotherException:
    do_another_thing()
          </code></pre>
        </section>
      </section>
      <section>
        <section>
          <h1><b>
                <span>Raising, Accessing and Propagating</span>
            </h1></b>
        </section>
        <section>
          <h3><b>Raising Exceptions</b></h3>
          <ul>
            <li>Exceptions can be raised with optional arguments.</li>
          </ul>
          <pre><code data-trim data-noescape class="hljs">
raise RuntimeError()
raise RuntimeError("error message")
          </code></pre>
        </section>
        <section>
          <h3><b>Accessing the Exception</b></h3>
           <ul>
            <li>Use "as" to access the exception object.</li>
          </ul>
<pre><code data-trim data-noescape class="hljs">
try:
    raise RuntimeError("oops")
except RuntimeError as e:
    print(e)
</code></pre>
        </section>
        <section>
          <h3><b>Propagating Exceptions</b></h3>
          <ul>
            <li>Try-blocks can be nested</li>
            <li>All exceptions propagate to the top-level "root exception handler" if uncaught</li>
          </ul>
          <pre><code data-trim data-noescape class="hljs">
try:
    try:
        raise Exception
    except Exception:
        print('Inner')
except Exception:
    print('Outer')
          </code></pre>
            <ul>
            <li>The (default) root exception handler terminates the Python process.</li>
          </ul>
        </section>
        <section>
          <h3><b>Propagating Exceptions</b></h3>
          <ul>
            <li>Propagation can be forced by using "raise" without arguments</li>
            <li>This re-raises the most recent exception</li>
          </ul>
          <pre><code data-trim data-noescape class="hljs">
try:
    try:
        raise Exception
    except Exception:
        print('Inner')
        raise
except Exception:
    print('Outer')
          </code></pre>
            <ul>
            <li>This is useful for e.g. exception logging.</li>
          </ul>
        </section>
      </section>
      <section>
        <section>
          <h1><b>
                <span>Finally and Else</span>
            </h1></b>
        </section>
        <section>
          <h3><b>Finally</b></h3>
          <ul>
            <li>Code in the finally block will always be executed (unless Python crashes completely)</li>
          </ul>
<pre><code data-trim data-noescape class="hljs">
try:
    open_file()
except IOError:
    print('Exception caught')
finally:
    close_file()
</code></pre>
        </section>
        <section>
          <h3><b>Else</b></h3>
          <ul>
            <li>Code in the else block will be executed when no exception is raised</li>
          </ul>
          <pre><code data-trim data-noescape class="hljs">
try:
    open_file()
except IOError:
    print('Exception caught')
else:
    print('Everything went according to plan')
          </code></pre>
        </section>
      </section>
      <section>
        <section>
          <h1><b>
          <span>Writing Exceptions</span>
      </h1></b>
        </section>
        <section>
          <h3><b>Inheritance</b></h3>
          <ul>
            <li>Exceptions are matched by superclass relationships</li>
            <ul>
                <li>RuntimeError</li>
                <li>StandardError</li>
                <li>Exception</li>
                <li>BaseException</li>
            </ul>
          </ul>
        </section>
        <section>
          <h3><b>Exception Matching</b></h3>
          <ul>
            <li>Exception hierarchies can be designed</li>
            <li>For example, OverflowError, ZeroDivisionError and FloatingPointError are all subclasses of ArithmeticError</li>
            <li>Just write a handler for ArithmeticError to catch any of them.</li>
          </ul>
        </section>
        <section>
          <h3><b>Writing Your Own</b></h3>
          <pre><code data-trim data-noescape class="hljs">
class MyException(Exception):
    pass
    </code></pre>
        </section>
      </section>
    </div>
  </div>

  <script src="reveal/lib/js/head.min.js"></script>
  <script src="reveal/js/reveal.js"></script>

  <script>
    // More info https://github.com/hakimel/reveal.js#configuration
    Reveal.initialize({
      controls: true,
      progress: true,
      history: true,
      center: true,
      slideNumber: true,
      transition: 'slide', // none/fade/slide/convex/concave/zoom
      // More info https://github.com/hakimel/reveal.js#dependencies
      dependencies: [{
          src: 'reveal/lib/js/classList.js',
          condition: function() {
            return !document.body.classList;
          }
        },
        {
          src: 'reveal/plugin/markdown/marked.js',
          condition: function() {
            return !!document.querySelector('[data-markdown]');
          }
        },
        {
          src: 'reveal/plugin/markdown/markdown.js',
          condition: function() {
            return !!document.querySelector('[data-markdown]');
          }
        },
        {
          src: 'reveal/plugin/highlight/highlight.js',
          async: true,
          callback: function() {
            hljs.initHighlightingOnLoad();
          }
        },
        {
          src: 'reveal/plugin/zoom-js/zoom.js',
          async: true
        },
        {
          src: 'reveal/plugin/notes/notes.js',
          async: true
        }
      ]
    });
  </script>

</body>

</html>
